name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: "Set version number"
        run: |
          python3 ${{ github.workspace }}/manage/update_manifest.py --version ${{ steps.version.outputs.version }}

      - name: Create zip
        run: |
          cd custom_components/sveasolar
          zip sveasolar.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/sveasolar/sveasolar.zip
          asset_name: sveasolar.zip
          tag: ${{ github.ref }}
          overwrite: true
